### ISSUE TITLE
New version fails to load in VS 2022 17.11.5

### ISSUE THREAD

**Issue by MagicAndre1981** [icnocop/PackageReferenceVersionToAttribute#5]
I've updated to last version and now I got a message at VS startup that a package failed to load. Looking in activitylog.xml shows this error:

```
SetSite failed for package [Package]Source: 'Community.VisualStudio.Toolkit.DependencyInjection.Microsoft' Description: Die Datei oder Assembly "Microsoft.Extensions.DependencyInjection, Version=5.0.0.2, Culture=neutral, PublicKeyToken=adb9793829ddae60" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
System.IO.FileNotFoundException: Die Datei oder Assembly "Microsoft.Extensions.DependencyInjection, Version=5.0.0.2, Culture=neutral, PublicKeyToken=adb9793829ddae60" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
File name: 'Microsoft.Extensions.DependencyInjection, Version=5.0.0.2, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Community.VisualStudio.Toolkit.DependencyInjection.Microsoft.MicrosoftDIToolkitPackage`1.CreateServiceCollection()
   at Community.VisualStudio.Toolkit.DependencyInjection.DIToolkitPackage`1.<InitializeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PackageReferenceVersionToAttributeExtension.Package.<InitializeAsync>d__1.MoveNext() in D:\a\PackageReferenceVersionToAttribute\PackageReferenceVersionToAttribute\src\PackageReferenceVersionToAttributeExtension\Package.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass17_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
```

So the very old version 5.0.0.2 of Microsoft.Extensions.DependencyInjection is missing.

The package Community.VisualStudio.Toolkit.DependencyInjection.Microsoft is deprecated according to nuget, so replace it:

![image](https://github.com/user-attachments/assets/4eb82c52-73bc-4066-bc37-a0580d569b99)

**Comment by icnocop** [comment]
Thank you for reporting this issue.

I just pushed another update to resolve this error.

Please update the extension to v1.0.1103.27.

Thank you.
